(() => {
  const copy = [
    ['Privacy policy', 'Politique de confidentialité', 'Política de privacidad'],
    ['Terms of service', 'Conditions d’utilisation', 'Términos de servicio'],
    ['Cookie policy', 'Politique relative aux cookies', 'Política de cookies'],
    ['Data deletion request', 'Demande de suppression des données', 'Solicitud de eliminación de datos'],
    ['Privacy choices', 'Choix de confidentialité', 'Opciones de privacidad'],
    ['Close', 'Fermer', 'Cerrar'],
    ['Only necessary storage', 'Stockage nécessaire uniquement', 'Solo almacenamiento necesario'],
    ['Third-party licenses', 'Licences tierces', 'Licencias de terceros'],
    ['PsyShelf uses local storage for your library and preferences. No analytics, advertising cookies or optional tracking are included. Automatic GitHub update checks are optional in settings.', 'PsyShelf stocke localement votre bibliothèque et vos préférences. Aucun suivi publicitaire, analytique ou facultatif. Les vérifications GitHub automatiques sont facultatives dans les paramètres.', 'PsyShelf almacena localmente tu biblioteca y preferencias. No incluye cookies de publicidad, analítica ni seguimiento opcional. Las comprobaciones automáticas de GitHub son opcionales en los ajustes.'],
    ['Policy version: 2026-10-02. Operator: OppositeThanks. Intended markets: France and Spain. Draft for review before public distribution: verify the operator’s legal identity and add a public privacy contact and business address. Contact details are not yet configured.', 'Version : 2026-10-02. Éditeur : OppositeThanks. Marchés prévus : France et Espagne. Projet à réviser avant distribution publique : vérifiez l’identité juridique et ajoutez un contact confidentialité public et une adresse professionnelle. Coordonnées non configurées.', 'Versión: 2026-10-02. Operador: OppositeThanks. Mercados previstos: Francia y España. Borrador pendiente de revisión antes de distribución pública: verifica la identidad legal y añade contacto público de privacidad y dirección profesional. Contacto aún sin configurar.'],
    ['PsyShelf stores resource metadata, file paths, managed copies, notes, annotations, reading progress, saved searches, extracted text/OCR and settings on your computer. Optional hardware scans stay local. No account, advertising, analytics or publisher-operated cloud service is included. Do not store patient records or identifiable clinical information.', 'PsyShelf conserve sur votre ordinateur les métadonnées, chemins, copies gérées, notes, annotations, progression, recherches, texte/OCR et paramètres. Les analyses matérielles facultatives restent locales. Aucun compte, publicité, analyse d’usage ou cloud de l’éditeur. Ne stockez pas de dossiers patients ni de données cliniques identifiables.', 'PsyShelf guarda en tu equipo metadatos, rutas, copias gestionadas, notas, anotaciones, progreso, búsquedas, texto/OCR y ajustes. Los análisis opcionales de hardware son locales. No incluye cuentas, publicidad, analítica ni nube del editor. No guardes historias clínicas ni datos clínicos identificables.'],
    ['AI actions send your question, relevant metadata and selected document excerpts to Ollama on 127.0.0.1. Ollama and model downloads are separate software with their own terms. Use a trusted local configuration; AI output may be wrong and is not clinical advice.', 'Les actions IA envoient votre question, les métadonnées utiles et des extraits à Ollama sur 127.0.0.1. Ollama et les modèles sont des logiciels distincts avec leurs propres conditions. Utilisez une configuration locale fiable ; les réponses peuvent être erronées et ne constituent pas un avis clinique.', 'Las acciones de IA envían tu pregunta, metadatos relevantes y extractos a Ollama en 127.0.0.1. Ollama y los modelos son software separado con sus propios términos. Usa una configuración local de confianza; las respuestas pueden ser incorrectas y no son asesoramiento clínico.'],
    ['Manual update checks and enabled automatic checks contact GitHub; downloads contact GitHub release infrastructure. Those services receive network information such as your IP address. Library content is not included in update requests. External links open in your browser under the destination’s policies. Cloud-folder backups are uploaded by your chosen sync provider, outside PsyShelf’s control.', 'Les vérifications manuelles ou automatiques activées contactent GitHub ; les téléchargements utilisent son infrastructure. Ces services reçoivent notamment votre adresse IP, sans contenu de bibliothèque. Les liens externes s’ouvrent dans votre navigateur selon les politiques du site. Votre fournisseur de synchronisation téléverse les sauvegardes cloud hors du contrôle de PsyShelf.', 'Las comprobaciones manuales o automáticas activadas contactan GitHub; las descargas usan su infraestructura. Esos servicios reciben datos de red como tu IP, sin contenido de la biblioteca. Los enlaces externos se abren en tu navegador bajo las políticas del destino. Tu proveedor de sincronización sube las copias en carpetas de nube fuera del control de PsyShelf.'],
    ['Data remains until you remove it. Deleting a catalog entry does not delete its file. Backups and safety copies persist until removed. Encryption and app lock are optional and do not guarantee protection against malware, other Windows programs or disk recovery. No publisher retention period or legal basis for support data can be finalized until the operator’s support process is defined.', 'Les données restent jusqu’à leur suppression. Supprimer une entrée ne supprime pas son fichier. Les sauvegardes persistent jusqu’à leur suppression. Chiffrement et verrouillage facultatifs ne garantissent pas une protection contre les logiciels malveillants, les autres programmes Windows ou la récupération disque. La conservation et la base juridique des données d’assistance dépendent du processus de l’éditeur à définir.', 'Los datos permanecen hasta su eliminación. Borrar una entrada no borra su archivo. Las copias permanecen hasta eliminarlas. El cifrado y bloqueo opcionales no garantizan protección contra malware, otros programas de Windows o recuperación del disco. La conservación y base jurídica de datos de soporte dependen del proceso del operador aún por definir.'],
    ['Use PsyShelf to organize resources you may lawfully access. You retain rights in your content and grant no publisher right to upload it. Confirm permission before sharing attachments; catalog inclusion is not a license to redistribute a work. Third-party software retains its own license terms. The application’s distribution license must be chosen by the publisher before release.', 'Utilisez PsyShelf pour organiser des ressources auxquelles vous avez légalement accès. Vous conservez vos droits sans autoriser l’éditeur à téléverser votre contenu. Vérifiez les droits avant partage ; une entrée ne permet pas de redistribuer une œuvre. Les logiciels tiers gardent leurs licences. L’éditeur doit choisir la licence de distribution de l’application avant publication.', 'Usa PsyShelf para organizar recursos a los que accedas legalmente. Conservas tus derechos y no autorizas al editor a subir tu contenido. Confirma permisos antes de compartir; una entrada no concede licencia para redistribuir una obra. El software de terceros mantiene sus licencias. El editor debe elegir la licencia de distribución de la aplicación antes del lanzamiento.'],
    ['PsyShelf is a resource organizer, not a medical device or diagnostic service. Verify original sources and AI results independently. Keep independent backups and recovery keys. Availability and accuracy are not guaranteed to the extent permitted by applicable law. Nothing in these terms excludes mandatory consumer rights or liability that cannot legally be excluded. Material changes must be disclosed before they apply; governing law and commercial terms require operator-specific review.', 'PsyShelf organise des ressources ; ce n’est pas un dispositif médical ni un service diagnostique. Vérifiez les sources et réponses IA. Conservez des sauvegardes et clés indépendantes. Disponibilité et exactitude ne sont pas garanties dans les limites légales. Aucun droit impératif ni responsabilité non excluable n’est supprimé. Les modifications substantielles doivent être annoncées ; droit applicable et conditions commerciales nécessitent une révision spécifique.', 'PsyShelf organiza recursos; no es un dispositivo médico ni un servicio diagnóstico. Verifica fuentes y respuestas de IA. Conserva copias y claves independientes. No se garantizan disponibilidad ni exactitud en la medida legalmente permitida. No se excluyen derechos obligatorios ni responsabilidades irrenunciables. Los cambios sustanciales deben comunicarse; ley aplicable y condiciones comerciales requieren revisión específica.'],
    ['The app does not set website cookies. Necessary local storage includes psyshelf-view (layout), psyshelf-privacy-notice-v1 (notice acknowledgement), the local library, settings and Chromium runtime storage. These remain locally until cleared or app data is deleted. The acknowledgement is not consent to tracking or acceptance of terms. There are no optional cookie categories to accept. Reopen Privacy choices at any time. Websites opened externally have separate cookie controls.', 'L’application ne définit pas de cookies web. Le stockage local nécessaire comprend psyshelf-view (présentation), psyshelf-privacy-notice-v1 (accusé de lecture), bibliothèque, paramètres et stockage Chromium. Il reste local jusqu’à suppression. L’accusé ne vaut ni consentement au suivi ni acceptation des conditions. Aucune catégorie facultative à accepter. Rouvrez les choix à tout moment. Les sites externes ont leurs propres contrôles.', 'La aplicación no establece cookies web. El almacenamiento local necesario incluye psyshelf-view (diseño), psyshelf-privacy-notice-v1 (aviso leído), biblioteca, ajustes y almacenamiento de Chromium. Permanece local hasta borrarlo. El aviso leído no es consentimiento de seguimiento ni aceptación de términos. No hay categorías opcionales que aceptar. Puedes reabrir las opciones cuando quieras. Los sitios externos tienen controles propios.'],
    ['To delete local data, open Settings → Uninstall PsyShelf… → Delete local data in an installed Windows copy. This removes the catalog, managed files, notes, settings, caches and safety copies. Referenced originals, external exports/backups, clipboard data and Ollama files remain: remove them separately, including synced cloud copies and recycle bins. Removing a resource alone preserves files. Clear the document index in library tools to remove extracted text without uninstalling.', 'Pour supprimer les données locales : Paramètres → Désinstaller PsyShelf… → Supprimer les données locales dans la version Windows installée. Catalogue, copies gérées, notes, paramètres, caches et copies de sécurité sont supprimés. Originaux, exports/sauvegardes externes, presse-papiers et fichiers Ollama restent : supprimez-les séparément, y compris cloud et corbeilles. Supprimer une ressource conserve les fichiers. Effacez l’index dans les outils pour supprimer le texte extrait sans désinstaller.', 'Para borrar datos locales: Ajustes → Desinstalar PsyShelf… → Eliminar datos locales en la copia instalada de Windows. Elimina catálogo, copias gestionadas, notas, ajustes, cachés y copias locales de seguridad. Quedan originales, exportaciones/copias externas, portapapeles y archivos de Ollama: bórralos aparte, también en nube y papeleras. Eliminar una entrada conserva archivos. Borra el índice desde las herramientas para eliminar texto extraído sin desinstalar.'],
    ['For information you separately send to the publisher, request access, correction or deletion through the verified privacy contact published with the release. Do not send your library, passwords or patient data. Include only a reply address and a description of the request; identity verification should be proportionate. Where GDPR applies, requests normally require a response within one month, with lawful exceptions. You may complain to your competent data protection authority. No request is transmitted by this screen; the contact channel is pending publisher configuration.', 'Pour les informations envoyées séparément à l’éditeur, demandez accès, rectification ou suppression via le contact vérifié publié avec la version. N’envoyez ni bibliothèque, mots de passe ni données patients. Fournissez seulement une adresse de réponse et la demande ; toute vérification doit être proportionnée. Sous le RGPD, le délai normal est d’un mois, avec exceptions légales. Vous pouvez saisir l’autorité compétente. Cet écran ne transmet rien ; le canal attend la configuration de l’éditeur.', 'Para información enviada aparte al editor, solicita acceso, rectificación o eliminación mediante el contacto verificado publicado con la versión. No envíes biblioteca, contraseñas ni datos de pacientes. Incluye solo dirección de respuesta y descripción; la verificación debe ser proporcionada. Bajo RGPD, el plazo normal es un mes, con excepciones legales. Puedes reclamar ante la autoridad competente. Esta pantalla no transmite solicitudes; falta configurar el contacto del editor.']
  ];
  const text = index => copy[index][{English:0,French:1,Spanish:2}[window.psyI18n.language] || 0];
  const host = document.createElement('section'); host.className = 'settings-section'; host.setAttribute('translate','no');
  document.getElementById('privacySection').append(host);
  const dialog = document.createElement('dialog'); dialog.setAttribute('translate','no');
  const card = document.createElement('div'); card.className='dialog-card settings-card'; dialog.append(card); document.body.append(dialog);
  const banner = document.createElement('section'); banner.className='privacy-notice'; banner.setAttribute('translate','no'); banner.setAttribute('aria-live','polite'); document.body.append(banner);
  let selected = null;
  const button = (index, action) => { const b=document.createElement('button'); b.type='button'; b.className='button ghost'; b.textContent=text(index); b.onclick=action; return b; };
  function renderDialog() {
    card.replaceChildren(); const h=document.createElement('h2'); h.textContent=text(selected); card.append(h); dialog.setAttribute('aria-label',text(selected));
    for (const index of [9, ...({0:[10,11,12,13],1:[14,15],2:[16],3:[17,18],4:[8,16]}[selected])]) { const p=document.createElement('p'); p.textContent=text(index); card.append(p); }
    card.append(button(5,()=>dialog.close()));
  }
  function show(index) { selected=index; renderDialog(); dialog.showModal(); }
  function render() {
    host.replaceChildren(); const row=document.createElement('div'); row.className='button-row'; host.append(row);
    for (let i=0;i<5;i++) row.append(button(i,()=> { if(i===4) banner.hidden=false; show(i); }));
    row.append(button(7,async()=> {
      const d=document.createElement('dialog'); d.setAttribute('aria-label',text(7));
      const c=document.createElement('div'); c.className='dialog-card settings-card';
      const pre=document.createElement('pre'); pre.className='legal-notices'; pre.setAttribute('translate','no');
      try { pre.textContent=await window.psyLibrary.legalNotices(); } catch { pre.textContent='renderer/third-party-notices.txt'; }
      c.append(pre,button(5,()=>{d.close();d.remove();})); d.append(c); document.body.append(d);d.showModal();
    }));
    banner.replaceChildren(); const p=document.createElement('p'); p.textContent=text(8); banner.append(p,button(2,()=>show(2)),button(6,()=> { try {localStorage.setItem('psyshelf-privacy-notice-v1','necessary-only');} catch {} banner.hidden=true; }));
    if(dialog.open) renderDialog();
  }
  try {banner.hidden=localStorage.getItem('psyshelf-privacy-notice-v1')==='necessary-only';} catch {}
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']}); render();
})();
